"""initial schema

Revision ID: 49822dc945f9
Revises: 
Create Date: 2026-07-20 13:15:39.406512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49822dc945f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('type', sa.Enum('transition', 'sound_effect', 'music', 'motion_graphic', 'broll', name='asset_type'), nullable=False),
    sa.Column('source', sa.Enum('internal', 'pexels', 'pixabay', name='asset_source'), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('r2_key', sa.Text(), nullable=False),
    sa.Column('license_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('styles',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('plan', sa.Enum('free', 'creator', 'pro', 'business', name='plan_tier'), nullable=False),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_table('billing_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('plan', sa.Enum('free', 'creator', 'pro', 'business', name='plan_tier'), nullable=False),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'processing', 'ready', 'failed', 'archived', name='project_status'), nullable=False),
    sa.Column('target_aspect_ratio', sa.Enum('9:16', '16:9', '1:1', name='aspect_ratio'), nullable=False),
    sa.Column('style_id', sa.UUID(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('remotion_composition_id', sa.Text(), nullable=False),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credits',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('monthly_grant', 'purchase', 'render_spend', 'refund', 'promo', name='credit_reason'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credits_user_created', 'credits', ['user_id', 'created_at'], unique=False)
    op.create_table('edit_plans',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('style_id', sa.UUID(), nullable=True),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('viral_score', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('generated', 'approved', 'superseded', name='edit_plan_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('proxy', 'metadata_extraction', 'edit_plan', 'render', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'retrying', name='job_status'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_project_status', 'jobs', ['project_id', 'status'], unique=False)
    op.create_table('source_videos',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('r2_key_raw', sa.Text(), nullable=False),
    sa.Column('r2_key_proxy', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'proxy_ready', 'metadata_ready', 'failed', name='source_video_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_videos_project_order', 'source_videos', ['project_id', 'order_index'], unique=False)
    op.create_table('metadata',
    sa.Column('source_video_id', sa.UUID(), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scene_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('silences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('speakers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_video_id')
    )
    op.create_table('timelines',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_edit_plan_id', sa.UUID(), nullable=True),
    sa.Column('state_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_edit_plan_id'], ['edit_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exports',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('timeline_id', sa.UUID(), nullable=False),
    sa.Column('aspect_ratio', sa.Enum('9:16', '16:9', '1:1', name='aspect_ratio'), nullable=False),
    sa.Column('quality', sa.Enum('720p', '1080p', '4k', name='export_quality'), nullable=False),
    sa.Column('r2_key_output', sa.Text(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exports')
    op.drop_table('timelines')
    op.drop_table('metadata')
    op.drop_index('ix_source_videos_project_order', table_name='source_videos')
    op.drop_table('source_videos')
    op.drop_index('ix_jobs_project_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('edit_plans')
    op.drop_index('ix_credits_user_created', table_name='credits')
    op.drop_table('credits')
    op.drop_table('templates')
    op.drop_table('projects')
    op.drop_table('billing_accounts')
    op.drop_table('users')
    op.drop_table('styles')
    op.drop_table('assets')
    # ### end Alembic commands ###

    # Autogenerate doesn't emit these: tables are gone but the ENUM types
    # they used aren't, since several types (aspect_ratio, plan_tier) are
    # shared across more than one table and Alembic won't guess it's safe to
    # drop them from a single table's drop_table call.
    for enum_name in (
        "asset_type",
        "asset_source",
        "plan_tier",
        "project_status",
        "aspect_ratio",
        "source_video_status",
        "edit_plan_status",
        "job_type",
        "job_status",
        "export_quality",
        "credit_reason",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
